# 表示使用第三代语法
version: '3'
# 用来表示 compose 需要启动的服务
services:

# mysql 服务配置
  mysql:
  # 容器名称
   container_name: v-mysql
   image: mysql/mysql-server:5.7
   # 环境变量
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
   # 对外开放端口
   ports:
   - "3306:3306"
   # 如果服务启动不成功会一直尝试
   restart: always
