# 表示使用第三代语法
version: '3'
# 用来表示 compose 需要启动的服务
services:

# mysql 服务配置
  mysql:
  # 容器名称
   container_name: v-mysql-node1
   image: mysql/mysql-server:5.7
   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
   # 环境变量
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
   # 对外开放端口: 宿主机端口：容器端口
   ports:
   - "3307:3306"
   # 如果服务启动不成功会一直尝试
   restart: always
   volumes:
   - ./mysql/db:/home/xiac/git-work/springboot2-docker/springboot2-docker-02/src/main/mysql/db

